name: SAST

on:
  push:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - name: Bearer Action
        uses: Bearer/bearer-action@v2
